import {
  type Incident,
  INCIDENT_STATUS,
  SEVERITY,
} from '@/features/incidents/types';

function minutesAgo(minutes: number): string {
  return new Date(Date.now() - minutes * 60_000).toISOString();
}

export const MOCK_INCIDENTS: Incident[] = [
  {
    id: 'INC-112',
    title: 'Database Outage',
    description:
      'Primary database cluster not responding, affecting all downstream services.',
    serviceName: 'Payment Processor',
    severity: SEVERITY.CRITICAL,
    status: INCIDENT_STATUS.OPEN,
    assignee: 'Alice Morgan',
    createdAt: minutesAgo(5),
    updatedAt: minutesAgo(2),
    notes: '',
  },
  {
    id: 'INC-111',
    title: 'High Latency on API',
    description:
      'API response times exceeding 3s on average across all endpoints.',
    serviceName: 'API Gateway',
    severity: SEVERITY.HIGH,
    status: INCIDENT_STATUS.OPEN,
    assignee: 'Bob Chen',
    createdAt: minutesAgo(12),
    updatedAt: minutesAgo(8),
    notes: '',
  },
  {
    id: 'INC-110',
    title: 'SSL Certificate Expiring',
    description: 'SSL certificate for cdn.cloudpulse.io expires in 7 days.',
    serviceName: 'CDN',
    severity: SEVERITY.MEDIUM,
    status: INCIDENT_STATUS.ACKNOWLEDGED,
    assignee: 'Alice Morgan',
    createdAt: minutesAgo(30),
    updatedAt: minutesAgo(20),
    notes: 'Renewal request submitted.',
  },
  {
    id: 'INC-109',
    title: 'Email Delivery Delay',
    description:
      'Outbound email queue backed up, delivery delayed by 15+ minutes.',
    serviceName: 'Notification Engine',
    severity: SEVERITY.LOW,
    status: INCIDENT_STATUS.RESOLVED,
    assignee: 'Carol Davis',
    createdAt: minutesAgo(60),
    updatedAt: minutesAgo(35),
    notes: 'Queue cleared after scaling up workers.',
  },
  {
    id: 'INC-108',
    title: 'Login Failures Spike',
    description:
      'Authentication failure rate jumped to 12% in the last 30 minutes.',
    serviceName: 'Auth Service',
    severity: SEVERITY.HIGH,
    status: INCIDENT_STATUS.OPEN,
    assignee: 'Bob Chen',
    createdAt: minutesAgo(90),
    updatedAt: minutesAgo(75),
    notes: '',
  },
  {
    id: 'INC-107',
    title: 'Data Sync Lag',
    description:
      'Replication lag between primary and replica exceeding 5 minutes.',
    serviceName: 'Data Pipeline',
    severity: SEVERITY.MEDIUM,
    status: INCIDENT_STATUS.ACKNOWLEDGED,
    assignee: 'Alice Morgan',
    createdAt: minutesAgo(120),
    updatedAt: minutesAgo(95),
    notes: 'Investigating upstream connector.',
  },
  {
    id: 'INC-106',
    title: 'CDN Cache Purge Failure',
    description: 'Cache invalidation requests failing on 3 of 8 edge nodes.',
    serviceName: 'CDN',
    severity: SEVERITY.HIGH,
    status: INCIDENT_STATUS.RESOLVED,
    assignee: 'Carol Davis',
    createdAt: minutesAgo(180),
    updatedAt: minutesAgo(140),
    notes: 'Cache nodes restarted successfully.',
  },
  {
    id: 'INC-105',
    title: 'Payment Timeout Errors',
    description: 'Payment gateway timing out on 8% of transactions.',
    serviceName: 'Payment Processor',
    severity: SEVERITY.CRITICAL,
    status: INCIDENT_STATUS.ACKNOWLEDGED,
    assignee: 'Bob Chen',
    createdAt: minutesAgo(240),
    updatedAt: minutesAgo(200),
    notes: 'Upstream provider notified.',
  },
  {
    id: 'INC-104',
    title: 'Push Notification Drops',
    description:
      'Approximately 5% of push notifications silently failing on iOS.',
    serviceName: 'Notification Engine',
    severity: SEVERITY.LOW,
    status: INCIDENT_STATUS.OPEN,
    assignee: 'Alice Morgan',
    createdAt: minutesAgo(300),
    updatedAt: minutesAgo(280),
    notes: '',
  },
  {
    id: 'INC-103',
    title: 'Rate Limiter Misconfigured',
    description:
      'Rate limit threshold set too low, blocking legitimate traffic.',
    serviceName: 'API Gateway',
    severity: SEVERITY.MEDIUM,
    status: INCIDENT_STATUS.RESOLVED,
    assignee: 'Bob Chen',
    createdAt: minutesAgo(420),
    updatedAt: minutesAgo(390),
    notes: 'Config corrected and deployed.',
  },
  {
    id: 'INC-102',
    title: 'Token Refresh Loop',
    description:
      'Client SDK entering infinite token refresh cycle under certain conditions.',
    serviceName: 'Auth Service',
    severity: SEVERITY.HIGH,
    status: INCIDENT_STATUS.RESOLVED,
    assignee: 'Carol Davis',
    createdAt: minutesAgo(600),
    updatedAt: minutesAgo(540),
    notes: 'Fixed infinite refresh bug in client SDK.',
  },
  {
    id: 'INC-101',
    title: 'Pipeline Backpressure Alert',
    description:
      'Ingestion pipeline approaching capacity limits during peak hours.',
    serviceName: 'Data Pipeline',
    severity: SEVERITY.LOW,
    status: INCIDENT_STATUS.ACKNOWLEDGED,
    assignee: 'Alice Morgan',
    createdAt: minutesAgo(720),
    updatedAt: minutesAgo(660),
    notes: 'Monitoring — no action needed yet.',
  },
];
